config/routes.rb
Rails.application.routes.draw do
  resources :globes do
    resources :points, except: [:index, :new, :show]
    collection { post :import }
  end

  get 'static/index'
  root 'static#index'

end

app/models/globe.rb
class Globe < ActiveRecord::Base
  has_many :points, dependent: :destroy

  validates :name, presence: true

end

app/models/point.rb
class Point < ActiveRecord::Base
  require 'csv'
  belongs_to :globe

  validates :state, presence: true
  validates :country, presence: true
  validates :magnitude, presence: true, numericality: true

  before_save -> { [city, state, country].each { |atr| atr.titleize } }

  def self.add_or_build(params)
    lat, lng = self.get_coordinates_for(params[:city], params[:state], params[:country])
    point = self.fetch_point_record_for lat, lng
    if point
      point.magnitude += params[:magnitude].to_f
    else 
      point = self.new(city: params[:city],
                      state: params[:state],
                      country: params[:country],
                      magnitude: params[:magnitude],
                      latitude: lat,
                      longitude: lng)
    end
    point
  end

  def self.import(file)
    # last = self.last
    # found_last = false

    CSV.foreach(file.path, headers: true, encoding: 'windows-1251:utf-8') do |row|
      data = row.to_hash

      # unless last && found_last
      #   if (data["city"].downcase == last.city.downcase && 
      #     data["state"].downcase == last.state.downcase && 
      #     data["country"].downcase == last.country.downcase)
      #     found_last = true
      #   else
      #     p data["city"] + data["state"] + data["country"]
      #     next
      #   end
      # end
      begin
        lat, lng = self.get_coordinates_for(data["city"], data["state"], data["country"])
        point = self.fetch_point_record_for lat, lng
        if point
          point.magnitude += data["count"].to_f
          point.save!
        else 
          point = self.create(city: data["city"],
                          state: data["state"],
                          country: data["country"],
                          magnitude: data["count"],
                          latitude: lat,
                          longitude: lng)
        end
      rescue
        sleep 1
        retry
      end
    end
  end

  def self.get_json(points)
    max_mag = 0

    points.each do |point|
      max_mag = point.magnitude if point.magnitude > max_mag
    end

    data = points.each_with_object([]) do |point, memo|
      memo.push point.latitude
      memo.push point.longitude
      memo.push (point.magnitude / max_mag)
    end
    data.as_json
  end

  private
    def self.get_coordinates_for(city, state, country)
      location = Geocoder.search "#{city}, #{state}, #{country}"
      location[0].coordinates.map! { |cor| cor.round(3) }
    end

    def self.fetch_point_record_for(lat, lng)
      self.where(latitude: lat, longitude: lng).first
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/globes_controller.rb
class GlobesController < ApplicationController
  before_action -> { @globe = Globe.find(params[:id]) }, except: [:index, :new, :create]
  def index
    redirect_to root_path
  end

  def new
    @globe = Globe.new
  end

  def create
    @globe = Globe.new(globe_params)
    if @globe.save
      redirect_to @globe
    else
      flash[:notice] = "Can't be blank"
      redirect_to root_path
    end
  end

  def show
    @points_json = Point.get_json @globe.points
  end

  def edit
  end

  def update
    if @globe.update(globe_params)
      redirect_to @globe
    else
      render 'edit'
    end
  end

  def destroy
    @globe.destroy
    flash[:notice] = "Globe #{@globe.name} destroyed"
    redirect_to root_path
  end

  def import
    @globe.points.import(params[:globe][:file])
    redirect_to @globe
  rescue
    redirect_to @globe
  end

  private 

    def globe_params
      params.require(:globe).permit(:name, :description)
    end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :find_globe_and_point, except: :create
  def create
    @globe = Globe.find(params[:globe_id])
    @point = @globe.points.add_or_build(point_params)
    
    respond_to do |format|
      if @point.save
        @points_json = Point.get_json @globe.points
        format.html { redirect_to @globe }
        format.js
      else
        format.html do 
          flash[:error] = "Can't create point, please check your input"
          redirect_to @globe
        end
        format.js
      end
    end
    
  end

  def edit

  end

  def update
    unless @point.update(point_params)
      flash[:error] = "Can't edit point, please check your input"
    end
    redirect_to @globe
  end

  def delete
    
  end


  private

    def point_params
      params.require(:point).permit(:city, :state, :country, :magnitude)
    end

    def find_globe_and_point
      @globe = Globe.find(params[:globe_id])
      @point = @globe.points.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/globes_helper.rb
module GlobesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/globes/_form.html.erb
<div id="new-globe-form">
  <%= form_for Globe.new do |f| %>
    <div class="form-component">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-component">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="form-component">
      <%= f.submit "New Globe" %>
    </div>
  <% end %>
</div>

app/views/globes/_globe.html.erb
<script type="text/javascript">
  function renderGlobe(raw_json) {
    if(!Detector.webgl){
      Detector.addGetWebGLMessage();
    } else {
      var globe = DAT.Globe(document.getElementById('container'), {    
        img: '<%= image_path "world.jpg" %>'
      });
      console.log(raw_json);
      var data = JSON.parse(raw_json);
      window.data = data;
      globe.addData(data, {format: 'magnitude'});
      globe.createPoints();
      globe.animate();

      document.body.style.backgroundImage = 'none'; // remove loading
    }
  }
  $(document).ready(renderGlobe('<%= @points_json %>'));
  
  $("#refresh").click(function(event){
    event.preventDefault();
    $("#container").html('');
    renderGlobe('<%= @points_json %>');
  });
</script>

app/views/globes/_import.html.erb
<%= form_for :globe, url: {action: :import, params: {id: @globe.id}} do |f| %>
  <div class="form-component"><%= f.file_field :file %></div>
  <div class="form-component"><%= f.submit "Import" %></div>
<% end %>
  

app/views/globes/index.html.erb
<h1><%= link_to "New", new_globe_path %></h1>

app/views/globes/new.html.erb
<%= form_for @globe do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.submit "Create" %>
<% end %>

app/views/globes/show.html.erb
<div id="container"></div>

<div id="title">
  <span><%= @globe.name.capitalize %></span>
  <a href="#" id="refresh"><i class="fa fa-refresh fa-2x fa-spin-hover"></i></a>
</div>
<div id="description">
  <%= @globe.description %>
</div>


<div id="side-bar">
  <div id="points-list">
    <a href="#" id="toggle"></a>
    <ul><%= render @globe.points %></ul>
  </div>

  <div id="add-point">
    <%= render 'points/form' %>
  </div>

  <div id="import">
    <%= render 'import' %>
  </div>
</div>

<div id="info">
  <strong>
    <a href="http://www.chromeexperiments.com/globe">WebGL Globe</a>
    <span class="bull">&bull;</span>
    <a href="http://www.github.com">Github</a>
  </strong> 
</div>

<%= render 'globe' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataGlobe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/points/_form.html.erb
<div id="point-form">
  <%= form_for [@globe, Point.new], remote: true do |f| %>
    <div class="form-component">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div class="form-component">
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>
    <div class="form-component">
      <%= f.label :country %>
      <%= f.text_field :country %>
    </div>
    <div class="form-component">
      <%= f.label :magnitude, "Value" %>
      <%= f.text_field :magnitude %>
    </div>
    <div class="form-component">
      <%= f.submit "Add New" %>
    </div>
  <% end %>
</div>

app/views/points/_point.html.erb
<li>
  <span class="city"><%= point.city %></span>
  <span class="state"><%= point.state %></span>
  <span class="country"><%= point.country %></span>
  <span class="magnitude"><%= point.magnitude %></span>
</li>

app/views/points/create.js.erb
$("#points-list ul").append("<%= j render @point if @point.valid? %>")
$("#container").html('');
renderGlobe('<%= @points_json %>');